// lib/features/freelancer/presentation/fl_work_history_screen.dart
//
// Freelancer Work History screen (FL-06).
// Chronological list of past events with PDF export placeholder.
//
// Layout:
//
//   ┌─────────────────────────────────────┐
//   │ AppBar: ← Work History             │
//   ├─────────────────────────────────────┤
//   │ Export PDF button                   │
//   ├─────────────────────────────────────┤
//   │ ListView                            │
//   │   HistoryRow | HistoryRow | ...     │
//   └─────────────────────────────────────┘

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/pdf/pdf_export.dart';
import '../../../shared/states/empty_state.dart';
import '../../../shared/states/error_state.dart';
import '../../../shared/states/lens_loader.dart';
import '../../../theme/app_colors.dart';
import '../application/fl_tools_providers.dart';

class FlWorkHistoryScreen extends ConsumerWidget {
  const FlWorkHistoryScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final async = ref.watch(flWorkHistoryProvider);

    return Scaffold(
      backgroundColor: AppColors.voidBlack,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: Icon(Icons.arrow_back, color: AppColors.film),
          onPressed: () => Navigator.of(context).maybePop(),
        ),
        title: Text(
          'Work History',
          style: TextStyle(
            color: AppColors.film,
            fontFamily: 'Poppins',
            fontSize: 22,
            fontWeight: FontWeight.w600,
          ),
        ),
        actions: [
          TextButton.icon(
            onPressed: () => _exportPdf(context, ref),
            icon: Icon(
              Icons.picture_as_pdf,
              color: AppColors.teal,
              size: 18,
            ),
            label: Text(
              'Export PDF',
              style: TextStyle(color: AppColors.teal, fontSize: 12),
            ),
          ),
        ],
      ),
      body: RefreshIndicator(
        color: AppColors.orange,
        backgroundColor: AppColors.voidLight,
        onRefresh: () async {
          ref.invalidate(flWorkHistoryProvider);
        },
        child: async.when(
          loading: () => const Center(child: LensLoader()),
          error: (_, _) => ErrorState(
            message: 'Failed to load work history.',
            onRetry: () => ref.invalidate(flWorkHistoryProvider),
          ),
          data: (items) {
            if (items.isEmpty) {
              return const EmptyState(
                message:
                    'No work history yet.\nCompleted events will appear here.',
                icon: Icons.history_outlined,
              );
            }
            return ListView.builder(
              padding: const EdgeInsets.symmetric(vertical: 8),
              itemCount: items.length,
              itemBuilder: (_, i) => _HistoryRow(event: items[i]),
            );
          },
        ),
      ),
    );
  }

  Future<void> _exportPdf(BuildContext context, WidgetRef ref) async {
    final messenger = ScaffoldMessenger.of(context);
    final items = ref.read(flWorkHistoryProvider).value ?? const [];
    if (items.isEmpty) {
      messenger.showSnackBar(
        SnackBar(content: Text('No history to export.')),
      );
      return;
    }
    String dateOf(Map<String, dynamic> e) {
      final raw = e['date'] as String?;
      if (raw == null) return '—';
      final d = DateTime.tryParse(raw);
      return d == null
          ? '—'
          : '${d.day.toString().padLeft(2, '0')}/'
                '${d.month.toString().padLeft(2, '0')}/${d.year}';
    }

    try {
      await PdfExporter.share(
        PdfDocumentData(
          documentTitle: 'Work History',
          fileName: 'work_history',
          subtitle: '${items.length} completed events',
          table: PdfTable(
            headers: const ['Date', 'Company', 'Type', 'Role'],
            rows: [
              for (final e in items)
                [
                  dateOf(e),
                  (e['companyName'] as String?) ?? 'Unknown',
                  (e['eventType'] as String?) ?? 'Event',
                  (e['role'] as String?) ?? '—',
                ],
            ],
          ),
          footnote: 'Generated by Clicker Pro',
        ),
      );
    } catch (e) {
      messenger.showSnackBar(
        SnackBar(content: Text('Could not create PDF: $e')),
      );
    }
  }
}

// ─── History Row ──────────────────────────────────────────────────────

class _HistoryRow extends StatelessWidget {
  const _HistoryRow({required this.event});

  final Map<String, dynamic> event;

  @override
  Widget build(BuildContext context) {
    final dateStr = event['date'] != null
        ? DateTime.parse(event['date'] as String)
        : null;
    final companyName = event['companyName'] as String? ?? 'Unknown';
    final eventType = event['eventType'] as String? ?? 'Event';
    final role = event['role'] as String? ?? '';

    final icons = {
      'wedding': Icons.favorite_outline,
      'holud': Icons.color_lens_outlined,
      'birthday': Icons.cake_outlined,
      'corporate': Icons.business_center_outlined,
      'preWedding': Icons.photo_camera_outlined,
      'anniversary': Icons.celebration_outlined,
      'outdoor': Icons.landscape_outlined,
      'other': Icons.event_outlined,
    };
    final icon = icons[eventType] ?? Icons.event_outlined;

    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
      padding: const EdgeInsets.all(14),
      decoration: AppColors.glassCardDecoration(),
      child: Row(
        children: [
          Container(
            width: 42,
            height: 42,
            decoration: AppColors.iconWrapDecoration(
              AppColors.teal.withValues(alpha: 0.12),
            ),
            child: Icon(icon, color: AppColors.teal, size: 20),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  companyName,
                  style: TextStyle(
                    color: AppColors.film,
                    fontSize: 14,
                    fontWeight: FontWeight.w500,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  eventType[0].toUpperCase() + eventType.substring(1),
                  style: TextStyle(
                    color: AppColors.filmDim,
                    fontSize: 12,
                  ),
                ),
              ],
            ),
          ),
          Column(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              if (dateStr != null)
                Text(
                  '${dateStr.month}/${dateStr.day}/${dateStr.year}',
                  style: TextStyle(
                    color: AppColors.filmMuted,
                    fontSize: 12,
                  ),
                ),
              if (role.isNotEmpty) ...[
                const SizedBox(height: 2),
                Container(
                  padding: const EdgeInsets.symmetric(
                    horizontal: 8,
                    vertical: 2,
                  ),
                  decoration: AppColors.pillChipDecoration(
                    tint: AppColors.purpleSoft,
                  ),
                  child: Text(
                    role,
                    style: TextStyle(
                      color: AppColors.purple,
                      fontSize: 10,
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ),
              ],
            ],
          ),
        ],
      ),
    );
  }
}
