import 'package:flutter/material.dart';

import '../../../core/pdf/pdf_export.dart';
import '../../../theme/app_colors.dart';

/// One month's cash-flow figures. Single source of truth shared by the
/// on-screen cards and the PDF export so they never drift apart.
class _MonthFlow {
  const _MonthFlow(this.month, this.solid, this.hatched, this.pending);
  final String month;
  final double solid;
  final double hatched;
  final double pending;
  double get total => solid + hatched + pending;
}

class CashFlowScreen extends StatelessWidget {
  const CashFlowScreen({super.key});

  static const List<_MonthFlow> _months = [
    _MonthFlow('June 2026', 85000, 32000, 15000),
    _MonthFlow('July 2026', 62000, 28000, 20000),
    _MonthFlow('August 2026', 45000, 18000, 35000),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.voidBlack,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: AppColors.film),
          onPressed: () => Navigator.of(context).maybePop(),
        ),
        title: const Text(
          'Cash Flow Timeline',
          style: TextStyle(
            color: AppColors.film,
            fontFamily: 'Poppins',
            fontSize: 22,
            fontWeight: FontWeight.w600,
          ),
        ),
        actions: [
          IconButton(
            icon: const Icon(
              Icons.picture_as_pdf_outlined,
              color: AppColors.gold,
            ),
            onPressed: () => _exportPdf(context),
          ),
        ],
      ),
      body: ListView(
        physics: const AlwaysScrollableScrollPhysics(),
        padding: const EdgeInsets.all(16),
        children: [
          for (final m in _months) ...[
            _buildMonthCard(
              m.month,
              solid: m.solid,
              hatched: m.hatched,
              pending: m.pending,
            ),
            const SizedBox(height: 12),
          ],
          const SizedBox(height: 12),
          _buildLegend(),
        ],
      ),
    );
  }

  Future<void> _exportPdf(BuildContext context) async {
    final messenger = ScaffoldMessenger.of(context);
    final grandTotal = _months.fold<double>(0, (s, m) => s + m.total);
    String f(double v) => '৳ ${v.toStringAsFixed(0)}';
    try {
      await PdfExporter.share(
        PdfDocumentData(
          documentTitle: 'Cash Flow Timeline',
          fileName: 'cash_flow_timeline',
          subtitle: '${_months.length}-month projection',
          summary: [
            PdfRow('Projected total', f(grandTotal), emphasize: true),
          ],
          table: PdfTable(
            headers: const ['Month', 'Solid', 'Hatched', 'Pending', 'Total'],
            rows: [
              for (final m in _months)
                [m.month, f(m.solid), f(m.hatched), f(m.pending), f(m.total)],
            ],
          ),
          footnote: 'Generated by Clicker Pro',
        ),
      );
    } catch (e) {
      messenger.showSnackBar(
        SnackBar(content: Text('PDF তৈরি করা যায়নি: $e')),
      );
    }
  }

  static Widget _buildMonthCard(
    String month, {
    required double solid,
    required double hatched,
    required double pending,
  }) {
    final total = solid + hatched + pending;
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: AppColors.glassCardDecoration(),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            month,
            style: const TextStyle(
              color: AppColors.film,
              fontSize: 16,
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(height: 12),
          _buildBar(solid, hatched, pending, total),
          const SizedBox(height: 12),
          Row(
            children: [
              _buildStat('Solid', solid, AppColors.teal),
              const SizedBox(width: 16),
              _buildStat('Hatched', hatched, AppColors.gold),
              const SizedBox(width: 16),
              _buildStat('Pending', pending, AppColors.filmMuted),
            ],
          ),
        ],
      ),
    );
  }

  static Widget _buildBar(
    double solid,
    double hatched,
    double pending,
    double total,
  ) {
    if (total == 0) {
      return Container(
        height: 8,
        decoration: BoxDecoration(
          color: AppColors.glass,
          borderRadius: BorderRadius.circular(4),
        ),
      );
    }
    return ClipRRect(
      borderRadius: BorderRadius.circular(4),
      child: SizedBox(
        height: 8,
        child: Row(
          children: [
            Expanded(
              flex: (solid / total * 1000).toInt(),
              child: Container(color: AppColors.teal),
            ),
            const SizedBox(width: 1),
            Expanded(
              flex: (hatched / total * 1000).toInt(),
              child: Container(color: AppColors.gold),
            ),
            const SizedBox(width: 1),
            Expanded(
              flex: (pending / total * 1000).toInt(),
              child: Container(
                decoration: BoxDecoration(
                  color: AppColors.filmMuted.withValues(alpha: 0.4),
                  border: Border.all(
                    color: AppColors.filmMuted.withValues(alpha: 0.6),
                    width: 1,
                  ),
                ),
                child: CustomPaint(painter: _HatchPainter()),
              ),
            ),
          ],
        ),
      ),
    );
  }

  static Widget _buildStat(String label, double value, Color color) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(
            color: AppColors.filmDim.withValues(alpha: 0.85),
            fontSize: 11,
          ),
        ),
        const SizedBox(height: 2),
        Text(
          value.toStringAsFixed(0),
          style: TextStyle(
            color: color,
            fontSize: 14,
            fontWeight: FontWeight.w600,
          ),
        ),
      ],
    );
  }

  static Widget _buildLegend() {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: AppColors.glassCardDecoration(),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Legend',
            style: TextStyle(
              color: AppColors.film,
              fontSize: 14,
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(height: 8),
          _legendItem(AppColors.teal, 'Solid \u2014 Confirmed income'),
          _legendItem(AppColors.gold, 'Hatched \u2014 Tentative bookings'),
          _legendItem(AppColors.filmMuted, 'Pending \u2014 Awaiting payment'),
        ],
      ),
    );
  }

  static Widget _legendItem(Color color, String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 6),
      child: Row(
        children: [
          Container(
            width: 12,
            height: 12,
            decoration: BoxDecoration(
              color: color,
              borderRadius: BorderRadius.circular(2),
            ),
          ),
          const SizedBox(width: 8),
          Text(
            text,
            style: TextStyle(
              color: AppColors.filmDim.withValues(alpha: 0.85),
              fontSize: 12,
            ),
          ),
        ],
      ),
    );
  }
}

class _HatchPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = AppColors.filmMuted.withValues(alpha: 0.3)
      ..strokeWidth = 1;

    for (double i = -size.height; i < size.width + size.height; i += 4) {
      canvas.drawLine(
        Offset(i, 0),
        Offset(i + size.height, size.height),
        paint,
      );
    }
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}
