// tool/check_coverage.dart
//
// CI gate: parse coverage/lcov.info, exclude generated files, and fail if
// the line-hit percentage falls below the configured floor।
//
// Run:
//   dart run tool/check_coverage.dart [--min=25] [--lcov=coverage/lcov.info]
//
// Defaults: --min=25 --lcov=coverage/lcov.info
//
// Excludes (always): *.g.dart (drift / json_serializable), *.freezed.dart,
// *.mocks.dart — these are autogenerated and hand-tested via the original
// source files।

import 'dart:io';

void main(List<String> args) async {
  var minPct = 25.0;
  var lcovPath = 'coverage/lcov.info';

  for (final raw in args) {
    if (raw.startsWith('--min=')) {
      minPct = double.parse(raw.substring(6));
    } else if (raw.startsWith('--lcov=')) {
      lcovPath = raw.substring(7);
    } else {
      stderr.writeln('Unknown arg: $raw');
      exit(64);
    }
  }

  final file = File(lcovPath);
  if (!await file.exists()) {
    stderr.writeln('lcov file not found: $lcovPath');
    stderr.writeln('Run `flutter test --coverage` first.');
    exit(2);
  }

  final lines = await file.readAsLines();

  // SF: <relative path> — start of a record per file
  // LF / LH — total / hit lines
  // end_of_record — close
  String? currentFile;
  var totalLf = 0;
  var totalLh = 0;
  var includedFiles = 0;
  var excludedFiles = 0;
  final perFile = <_FileCov>[];

  int? curLf;
  int? curLh;

  bool isExcluded(String path) {
    return path.endsWith('.g.dart') ||
        path.endsWith('.freezed.dart') ||
        path.endsWith('.mocks.dart') ||
        path.contains('/generated/') ||
        path.contains('\\generated\\');
  }

  for (final line in lines) {
    if (line.startsWith('SF:')) {
      currentFile = line.substring(3);
      curLf = curLh = null;
    } else if (line.startsWith('LF:')) {
      curLf = int.parse(line.substring(3));
    } else if (line.startsWith('LH:')) {
      curLh = int.parse(line.substring(3));
    } else if (line == 'end_of_record' && currentFile != null) {
      if (!isExcluded(currentFile)) {
        totalLf += curLf ?? 0;
        totalLh += curLh ?? 0;
        includedFiles++;
        perFile.add(_FileCov(currentFile, curLf ?? 0, curLh ?? 0));
      } else {
        excludedFiles++;
      }
      currentFile = null;
    }
  }

  if (totalLf == 0) {
    stderr.writeln(
      'No coverable lines found after exclusions — nothing to gate.',
    );
    exit(2);
  }

  final pct = totalLh / totalLf * 100;
  stdout.writeln('═══ Flutter coverage gate ═══');
  stdout.writeln('  files included : $includedFiles');
  stdout.writeln('  files excluded : $excludedFiles (generated)');
  stdout.writeln('  lines hit      : $totalLh / $totalLf');
  stdout.writeln('  coverage       : ${pct.toStringAsFixed(2)}%');
  stdout.writeln('  threshold      : ${minPct.toStringAsFixed(2)}%');

  // Top 5 worst-covered files (helpful CI hint, surfaces regressions)
  perFile.sort((a, b) {
    final ap = a.lf == 0 ? 100 : a.lh / a.lf;
    final bp = b.lf == 0 ? 100 : b.lh / b.lf;
    return ap.compareTo(bp);
  });
  stdout.writeln('  bottom 5 files :');
  for (final f in perFile.take(5)) {
    final p = f.lf == 0 ? 0 : (f.lh / f.lf * 100);
    stdout.writeln('    ${p.toStringAsFixed(1).padLeft(5)}%  ${f.file}');
  }

  if (pct + 1e-9 < minPct) {
    stdout.writeln('═══ FAIL ═══ coverage below threshold');
    exit(1);
  }
  stdout.writeln('═══ OK ═══');
}

class _FileCov {
  _FileCov(this.file, this.lf, this.lh);
  final String file;
  final int lf;
  final int lh;
}
