// lib/core/pdf/pdf_export.dart
//
// Shared PDF export helper used by every "Export PDF" button in the app
// (invoice, cash flow, petty cash, salary sheet, freelancer history,
// booking delivery). Screens describe their document declaratively with a
// [PdfDocumentData] — a title, a few summary key/value rows, and an optional
// table — and this builder renders a clean, Orange-Horizon-themed A4 page,
// then opens the native share/print sheet via the `printing` package.
//
// Keeping all the pdf/widget code in one place means the screens stay free of
// layout details and every exported document looks consistent.

import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

/// One labelled value shown in the summary block, e.g. ("Total", "৳ 25,000").
class PdfRow {
  const PdfRow(this.label, this.value, {this.emphasize = false});
  final String label;
  final String value;

  /// Render the value larger / brand-coloured (used for the headline figure).
  final bool emphasize;
}

/// An optional line-item table: a header row plus body rows. Each row is a
/// list of cells matching [headers] in length.
class PdfTable {
  const PdfTable({required this.headers, required this.rows});
  final List<String> headers;
  final List<List<String>> rows;
}

/// Declarative description of a document to export.
class PdfDocumentData {
  const PdfDocumentData({
    required this.documentTitle,
    required this.fileName,
    this.companyName = '',
    this.companyPhone = '',
    this.subtitle = '',
    this.summary = const <PdfRow>[],
    this.table,
    this.footnote = '',
  });

  /// Big heading at the top of the page, e.g. "Invoice", "Salary Sheet".
  final String documentTitle;

  /// Base name for the shared file (no extension), e.g. "invoice_AB12".
  final String fileName;

  final String companyName;
  final String companyPhone;

  /// Small line under the title, e.g. the booking title or month.
  final String subtitle;

  final List<PdfRow> summary;
  final PdfTable? table;

  /// Small grey note at the bottom (e.g. "Generated by Clicker Pro").
  final String footnote;
}

class PdfExporter {
  PdfExporter._();

  // Brand palette mirrored from AppColors so the PDF matches the app.
  static const PdfColor _orange = PdfColor.fromInt(0xFFFF6B00);
  static const PdfColor _ink = PdfColor.fromInt(0xFF111827);
  static const PdfColor _dim = PdfColor.fromInt(0xFF6B7280);
  static const PdfColor _surfaceAlt = PdfColor.fromInt(0xFFF1F5F9);
  static const PdfColor _line = PdfColor.fromInt(0xFFE5E7EB);

  /// The bundled Inter font has no glyph for the Bengali taka sign (৳, U+09F3)
  /// — it would render as an empty "tofu" box in the PDF. Swap it for the
  /// ASCII "Tk" so amounts always read correctly. (Only affects the PDF; the
  /// in-app UI keeps using ৳.)
  static String _safe(String s) => s.replaceAll('৳', 'Tk');

  /// Builds the document and opens the native share/print sheet.
  /// Returns false if the user dismissed the sheet without sharing.
  static Future<bool> share(PdfDocumentData data) async {
    final bytes = await build(data);
    return Printing.sharePdf(bytes: bytes, filename: '${data.fileName}.pdf');
  }

  /// Builds the PDF and returns the raw bytes (useful for tests / preview).
  static Future<Uint8List> build(PdfDocumentData data) async {
    final doc = pw.Document();

    // Use the bundled Inter/Roboto-style fonts shipped with the `pdf`
    // package; they cover Latin + Bengali digits rendered as ASCII. Bengali
    // script glyphs need a embedded font — fall back gracefully if absent.
    final theme = await _theme();

    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        theme: theme,
        margin: const pw.EdgeInsets.all(36),
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            _header(data),
            pw.SizedBox(height: 24),
            if (data.summary.isNotEmpty) _summaryBlock(data.summary),
            if (data.table != null) ...[
              pw.SizedBox(height: 20),
              _table(data.table!),
            ],
            pw.Spacer(),
            if (data.footnote.isNotEmpty) _footer(data.footnote),
          ],
        ),
      ),
    );

    return doc.save();
  }

  static Future<pw.ThemeData> _theme() async {
    try {
      final regular = await PdfGoogleFonts.interRegular();
      final bold = await PdfGoogleFonts.interBold();
      return pw.ThemeData.withFont(base: regular, bold: bold);
    } catch (_) {
      // Offline / font fetch failed — fall back to built-in Helvetica.
      return pw.ThemeData.base();
    }
  }

  static pw.Widget _header(PdfDocumentData data) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  _safe(data.documentTitle),
                  style: pw.TextStyle(
                    fontSize: 26,
                    fontWeight: pw.FontWeight.bold,
                    color: _ink,
                  ),
                ),
                if (data.subtitle.isNotEmpty) ...[
                  pw.SizedBox(height: 4),
                  pw.Text(
                    _safe(data.subtitle),
                    style: pw.TextStyle(fontSize: 12, color: _dim),
                  ),
                ],
              ],
            ),
            if (data.companyName.isNotEmpty)
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  pw.Text(
                    _safe(data.companyName),
                    style: pw.TextStyle(
                      fontSize: 14,
                      fontWeight: pw.FontWeight.bold,
                      color: _orange,
                    ),
                  ),
                  if (data.companyPhone.isNotEmpty)
                    pw.Text(
                      _safe(data.companyPhone),
                      style: pw.TextStyle(fontSize: 11, color: _dim),
                    ),
                ],
              ),
          ],
        ),
        pw.SizedBox(height: 12),
        pw.Container(height: 3, color: _orange, width: 64),
      ],
    );
  }

  static pw.Widget _summaryBlock(List<PdfRow> rows) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: _surfaceAlt,
        borderRadius: pw.BorderRadius.circular(10),
      ),
      child: pw.Column(
        children: [
          for (final r in rows)
            pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 5),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    _safe(r.label),
                    style: pw.TextStyle(
                      fontSize: r.emphasize ? 13 : 11,
                      color: _dim,
                    ),
                  ),
                  pw.Text(
                    _safe(r.value),
                    style: pw.TextStyle(
                      fontSize: r.emphasize ? 16 : 12,
                      fontWeight: pw.FontWeight.bold,
                      color: r.emphasize ? _orange : _ink,
                    ),
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }

  static pw.Widget _table(PdfTable table) {
    return pw.TableHelper.fromTextArray(
      headers: table.headers.map(_safe).toList(),
      data: table.rows
          .map((row) => row.map(_safe).toList())
          .toList(),
      border: pw.TableBorder.symmetric(
        inside: pw.BorderSide(color: _line, width: 0.5),
      ),
      headerStyle: pw.TextStyle(
        fontSize: 10,
        fontWeight: pw.FontWeight.bold,
        color: PdfColors.white,
      ),
      headerDecoration: const pw.BoxDecoration(color: _orange),
      cellStyle: pw.TextStyle(fontSize: 10, color: _ink),
      cellHeight: 26,
      oddRowDecoration: const pw.BoxDecoration(color: _surfaceAlt),
      cellAlignments: {
        for (var i = 0; i < table.headers.length; i++)
          i: i == 0 ? pw.Alignment.centerLeft : pw.Alignment.centerRight,
      },
    );
  }

  static pw.Widget _footer(String note) {
    return pw.Container(
      alignment: pw.Alignment.center,
      child: pw.Text(
        _safe(note),
        style: pw.TextStyle(fontSize: 9, color: _dim),
      ),
    );
  }
}
